title: Skills Showcase
email: mateusz.karlowski@zoho.com
markdown: GFM
description: >-
   My skills showcase in one place with practical example using them.
baseurl: "https://mati2251.github.io/" 
url: "skills-showcase" 
github_username:  mati2251
linkedin_username: mateusz-kar≈Çowski-8500a1184
theme: minima
plugins:
  - jekyll-feed
  - jemoji